/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.mal.projectaladdin.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import it.mal.projectaladdin.model.Wishlist;
import it.mal.projectaladdin.service.CategoryLocalService;
import it.mal.projectaladdin.service.CategoryWishlistLocalService;
import it.mal.projectaladdin.service.WishLocalService;
import it.mal.projectaladdin.service.WishlistLocalService;
import it.mal.projectaladdin.service.persistence.CategoryPersistence;
import it.mal.projectaladdin.service.persistence.CategoryWishlistPersistence;
import it.mal.projectaladdin.service.persistence.WishPersistence;
import it.mal.projectaladdin.service.persistence.WishlistPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the wishlist local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.mal.projectaladdin.service.impl.WishlistLocalServiceImpl}.
 * </p>
 *
 * @author MAL
 * @see it.mal.projectaladdin.service.impl.WishlistLocalServiceImpl
 * @see it.mal.projectaladdin.service.WishlistLocalServiceUtil
 * @generated
 */
public abstract class WishlistLocalServiceBaseImpl
	implements WishlistLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link it.mal.projectaladdin.service.WishlistLocalServiceUtil} to access the wishlist local service.
	 */

	/**
	 * Adds the wishlist to the database. Also notifies the appropriate model listeners.
	 *
	 * @param wishlist the wishlist
	 * @return the wishlist that was added
	 * @throws SystemException if a system exception occurred
	 */
	public Wishlist addWishlist(Wishlist wishlist) throws SystemException {
		wishlist.setNew(true);

		wishlist = wishlistPersistence.update(wishlist, false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(wishlist);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return wishlist;
	}

	/**
	 * Creates a new wishlist with the primary key. Does not add the wishlist to the database.
	 *
	 * @param wishlistId the primary key for the new wishlist
	 * @return the new wishlist
	 */
	public Wishlist createWishlist(long wishlistId) {
		return wishlistPersistence.create(wishlistId);
	}

	/**
	 * Deletes the wishlist with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param wishlistId the primary key of the wishlist
	 * @throws PortalException if a wishlist with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteWishlist(long wishlistId)
		throws PortalException, SystemException {
		Wishlist wishlist = wishlistPersistence.remove(wishlistId);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(wishlist);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the wishlist from the database. Also notifies the appropriate model listeners.
	 *
	 * @param wishlist the wishlist
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteWishlist(Wishlist wishlist) throws SystemException {
		wishlistPersistence.remove(wishlist);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(wishlist);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return wishlistPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return wishlistPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return wishlistPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return wishlistPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public Wishlist fetchWishlist(long wishlistId) throws SystemException {
		return wishlistPersistence.fetchByPrimaryKey(wishlistId);
	}

	/**
	 * Returns the wishlist with the primary key.
	 *
	 * @param wishlistId the primary key of the wishlist
	 * @return the wishlist
	 * @throws PortalException if a wishlist with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public Wishlist getWishlist(long wishlistId)
		throws PortalException, SystemException {
		return wishlistPersistence.findByPrimaryKey(wishlistId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return wishlistPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the wishlists.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of wishlists
	 * @param end the upper bound of the range of wishlists (not inclusive)
	 * @return the range of wishlists
	 * @throws SystemException if a system exception occurred
	 */
	public List<Wishlist> getWishlists(int start, int end)
		throws SystemException {
		return wishlistPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of wishlists.
	 *
	 * @return the number of wishlists
	 * @throws SystemException if a system exception occurred
	 */
	public int getWishlistsCount() throws SystemException {
		return wishlistPersistence.countAll();
	}

	/**
	 * Updates the wishlist in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param wishlist the wishlist
	 * @return the wishlist that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public Wishlist updateWishlist(Wishlist wishlist) throws SystemException {
		return updateWishlist(wishlist, true);
	}

	/**
	 * Updates the wishlist in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param wishlist the wishlist
	 * @param merge whether to merge the wishlist with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the wishlist that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public Wishlist updateWishlist(Wishlist wishlist, boolean merge)
		throws SystemException {
		wishlist.setNew(false);

		wishlist = wishlistPersistence.update(wishlist, merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(wishlist);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return wishlist;
	}

	/**
	 * Returns the category local service.
	 *
	 * @return the category local service
	 */
	public CategoryLocalService getCategoryLocalService() {
		return categoryLocalService;
	}

	/**
	 * Sets the category local service.
	 *
	 * @param categoryLocalService the category local service
	 */
	public void setCategoryLocalService(
		CategoryLocalService categoryLocalService) {
		this.categoryLocalService = categoryLocalService;
	}

	/**
	 * Returns the category persistence.
	 *
	 * @return the category persistence
	 */
	public CategoryPersistence getCategoryPersistence() {
		return categoryPersistence;
	}

	/**
	 * Sets the category persistence.
	 *
	 * @param categoryPersistence the category persistence
	 */
	public void setCategoryPersistence(CategoryPersistence categoryPersistence) {
		this.categoryPersistence = categoryPersistence;
	}

	/**
	 * Returns the category wishlist local service.
	 *
	 * @return the category wishlist local service
	 */
	public CategoryWishlistLocalService getCategoryWishlistLocalService() {
		return categoryWishlistLocalService;
	}

	/**
	 * Sets the category wishlist local service.
	 *
	 * @param categoryWishlistLocalService the category wishlist local service
	 */
	public void setCategoryWishlistLocalService(
		CategoryWishlistLocalService categoryWishlistLocalService) {
		this.categoryWishlistLocalService = categoryWishlistLocalService;
	}

	/**
	 * Returns the category wishlist persistence.
	 *
	 * @return the category wishlist persistence
	 */
	public CategoryWishlistPersistence getCategoryWishlistPersistence() {
		return categoryWishlistPersistence;
	}

	/**
	 * Sets the category wishlist persistence.
	 *
	 * @param categoryWishlistPersistence the category wishlist persistence
	 */
	public void setCategoryWishlistPersistence(
		CategoryWishlistPersistence categoryWishlistPersistence) {
		this.categoryWishlistPersistence = categoryWishlistPersistence;
	}

	/**
	 * Returns the wish local service.
	 *
	 * @return the wish local service
	 */
	public WishLocalService getWishLocalService() {
		return wishLocalService;
	}

	/**
	 * Sets the wish local service.
	 *
	 * @param wishLocalService the wish local service
	 */
	public void setWishLocalService(WishLocalService wishLocalService) {
		this.wishLocalService = wishLocalService;
	}

	/**
	 * Returns the wish persistence.
	 *
	 * @return the wish persistence
	 */
	public WishPersistence getWishPersistence() {
		return wishPersistence;
	}

	/**
	 * Sets the wish persistence.
	 *
	 * @param wishPersistence the wish persistence
	 */
	public void setWishPersistence(WishPersistence wishPersistence) {
		this.wishPersistence = wishPersistence;
	}

	/**
	 * Returns the wishlist local service.
	 *
	 * @return the wishlist local service
	 */
	public WishlistLocalService getWishlistLocalService() {
		return wishlistLocalService;
	}

	/**
	 * Sets the wishlist local service.
	 *
	 * @param wishlistLocalService the wishlist local service
	 */
	public void setWishlistLocalService(
		WishlistLocalService wishlistLocalService) {
		this.wishlistLocalService = wishlistLocalService;
	}

	/**
	 * Returns the wishlist persistence.
	 *
	 * @return the wishlist persistence
	 */
	public WishlistPersistence getWishlistPersistence() {
		return wishlistPersistence;
	}

	/**
	 * Sets the wishlist persistence.
	 *
	 * @param wishlistPersistence the wishlist persistence
	 */
	public void setWishlistPersistence(WishlistPersistence wishlistPersistence) {
		this.wishlistPersistence = wishlistPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("it.mal.projectaladdin.model.Wishlist",
			wishlistLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"it.mal.projectaladdin.model.Wishlist");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return Wishlist.class;
	}

	protected String getModelClassName() {
		return Wishlist.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = wishlistPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = CategoryLocalService.class)
	protected CategoryLocalService categoryLocalService;
	@BeanReference(type = CategoryPersistence.class)
	protected CategoryPersistence categoryPersistence;
	@BeanReference(type = CategoryWishlistLocalService.class)
	protected CategoryWishlistLocalService categoryWishlistLocalService;
	@BeanReference(type = CategoryWishlistPersistence.class)
	protected CategoryWishlistPersistence categoryWishlistPersistence;
	@BeanReference(type = WishLocalService.class)
	protected WishLocalService wishLocalService;
	@BeanReference(type = WishPersistence.class)
	protected WishPersistence wishPersistence;
	@BeanReference(type = WishlistLocalService.class)
	protected WishlistLocalService wishlistLocalService;
	@BeanReference(type = WishlistPersistence.class)
	protected WishlistPersistence wishlistPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private static Log _log = LogFactoryUtil.getLog(WishlistLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}