/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.mal.projectaladdin.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Wishlist service. Represents a row in the &quot;ALD_Wishlist&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.mal.projectaladdin.model.impl.WishlistModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.mal.projectaladdin.model.impl.WishlistImpl}.
 * </p>
 *
 * @author MAL
 * @see Wishlist
 * @see it.mal.projectaladdin.model.impl.WishlistImpl
 * @see it.mal.projectaladdin.model.impl.WishlistModelImpl
 * @generated
 */
public interface WishlistModel extends BaseModel<Wishlist> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wishlist model instance should use the {@link Wishlist} interface instead.
	 */

	/**
	 * Returns the primary key of this wishlist.
	 *
	 * @return the primary key of this wishlist
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wishlist.
	 *
	 * @param primaryKey the primary key of this wishlist
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the wishlist ID of this wishlist.
	 *
	 * @return the wishlist ID of this wishlist
	 */
	public long getWishlistId();

	/**
	 * Sets the wishlist ID of this wishlist.
	 *
	 * @param wishlistId the wishlist ID of this wishlist
	 */
	public void setWishlistId(long wishlistId);

	/**
	 * Returns the user ID of this wishlist.
	 *
	 * @return the user ID of this wishlist
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this wishlist.
	 *
	 * @param userId the user ID of this wishlist
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this wishlist.
	 *
	 * @return the user uuid of this wishlist
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this wishlist.
	 *
	 * @param userUuid the user uuid of this wishlist
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the wish ID of this wishlist.
	 *
	 * @return the wish ID of this wishlist
	 */
	public long getWishId();

	/**
	 * Sets the wish ID of this wishlist.
	 *
	 * @param wishId the wish ID of this wishlist
	 */
	public void setWishId(long wishId);

	/**
	 * Returns the rating of this wishlist.
	 *
	 * @return the rating of this wishlist
	 */
	public int getRating();

	/**
	 * Sets the rating of this wishlist.
	 *
	 * @param rating the rating of this wishlist
	 */
	public void setRating(int rating);

	/**
	 * Returns the comment of this wishlist.
	 *
	 * @return the comment of this wishlist
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this wishlist.
	 *
	 * @param comment the comment of this wishlist
	 */
	public void setComment(String comment);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Wishlist wishlist);

	public int hashCode();

	public CacheModel<Wishlist> toCacheModel();

	public Wishlist toEscapedModel();

	public String toString();

	public String toXmlString();
}