/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.mal.projectaladdin.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Wish service. Represents a row in the &quot;ALD_Wish&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.mal.projectaladdin.model.impl.WishModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.mal.projectaladdin.model.impl.WishImpl}.
 * </p>
 *
 * @author MAL
 * @see Wish
 * @see it.mal.projectaladdin.model.impl.WishImpl
 * @see it.mal.projectaladdin.model.impl.WishModelImpl
 * @generated
 */
public interface WishModel extends BaseModel<Wish> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wish model instance should use the {@link Wish} interface instead.
	 */

	/**
	 * Returns the primary key of this wish.
	 *
	 * @return the primary key of this wish
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wish.
	 *
	 * @param primaryKey the primary key of this wish
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the wish ID of this wish.
	 *
	 * @return the wish ID of this wish
	 */
	public long getWishId();

	/**
	 * Sets the wish ID of this wish.
	 *
	 * @param wishId the wish ID of this wish
	 */
	public void setWishId(long wishId);

	/**
	 * Returns the name of this wish.
	 *
	 * @return the name of this wish
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this wish.
	 *
	 * @param name the name of this wish
	 */
	public void setName(String name);

	/**
	 * Returns the description of this wish.
	 *
	 * @return the description of this wish
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this wish.
	 *
	 * @param description the description of this wish
	 */
	public void setDescription(String description);

	/**
	 * Returns the price of this wish.
	 *
	 * @return the price of this wish
	 */
	public double getPrice();

	/**
	 * Sets the price of this wish.
	 *
	 * @param price the price of this wish
	 */
	public void setPrice(double price);

	/**
	 * Returns the url of this wish.
	 *
	 * @return the url of this wish
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this wish.
	 *
	 * @param url the url of this wish
	 */
	public void setUrl(String url);

	/**
	 * Returns the image of this wish.
	 *
	 * @return the image of this wish
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this wish.
	 *
	 * @param image the image of this wish
	 */
	public void setImage(String image);

	/**
	 * Returns the creation date of this wish.
	 *
	 * @return the creation date of this wish
	 */
	public Date getCreationDate();

	/**
	 * Sets the creation date of this wish.
	 *
	 * @param creationDate the creation date of this wish
	 */
	public void setCreationDate(Date creationDate);

	/**
	 * Returns the modified date of this wish.
	 *
	 * @return the modified date of this wish
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this wish.
	 *
	 * @param modifiedDate the modified date of this wish
	 */
	public void setModifiedDate(Date modifiedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Wish wish);

	public int hashCode();

	public CacheModel<Wish> toCacheModel();

	public Wish toEscapedModel();

	public String toString();

	public String toXmlString();
}