/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.mal.projectaladdin.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import it.mal.projectaladdin.model.Wish;
import it.mal.projectaladdin.service.WishLocalServiceUtil;

/**
 * The extended model base implementation for the Wish service. Represents a row in the &quot;ALD_Wish&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WishImpl}.
 * </p>
 *
 * @author MAL
 * @see WishImpl
 * @see it.mal.projectaladdin.model.Wish
 * @generated
 */
public abstract class WishBaseImpl extends WishModelImpl implements Wish {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a wish model instance should use the {@link Wish} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			WishLocalServiceUtil.addWish(this);
		}
		else {
			WishLocalServiceUtil.updateWish(this);
		}
	}
}